create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  organization_id bigint null,
  project_id bigint null,
  technician_id uuid null,
  log_date date not null default current_date,
  shift text null,
  weather_summary text null,
  supervisor_name text null,
  status text not null default 'draft',
  submitted_at timestamptz null,
  approved_at timestamptz null,
  returned_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Columns that drifted onto daily_logs outside the migration history (see the
-- tail of 001_base_schema, which can only add them when the table pre-exists).
-- On a fresh database they are added here, right after the table is created.
alter table public.daily_logs add column if not exists client_log_id text;
alter table public.daily_logs add column if not exists submitted_by uuid;
alter table public.daily_logs add column if not exists signature_id uuid;
alter table public.daily_logs add column if not exists pdf_url text;
alter table public.daily_logs add column if not exists payload jsonb default '{}'::jsonb;
alter table public.daily_logs add column if not exists pdf_generated boolean default false;

-- daily_log_signatures is created in 001_base_schema, before daily_logs
-- exists; on a fresh database its FK to daily_logs is added here instead.
do $$ begin
  if to_regclass('public.daily_log_signatures') is not null
     and not exists (select 1 from pg_constraint where conname = 'daily_log_signatures_daily_log_id_fkey') then
    alter table public.daily_log_signatures add constraint daily_log_signatures_daily_log_id_fkey FOREIGN KEY (daily_log_id) REFERENCES public.daily_logs(id) ON DELETE CASCADE;
  end if;
end $$;

create table if not exists public.daily_log_activities (
  id bigint generated by default as identity primary key,
  daily_log_id bigint not null references public.daily_logs(id) on delete cascade,
  activity_type text not null,
  title text not null,
  description text null,
  location text null,
  start_time time null,
  end_time time null,
  crew_size text null,
  equipment_used text null,
  material_used text null,
  status text not null default 'not_started',
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_log_activity_reports (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.daily_log_activities(id) on delete cascade,
  report_type text not null,
  linked_report_table text null,
  linked_report_id bigint null,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);

create table if not exists public.daily_log_activity_photos (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.daily_log_activities(id) on delete cascade,
  file_name text not null,
  storage_path text not null,
  compressed_storage_path text null,
  caption text null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_log_comments (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.daily_log_activities(id) on delete cascade,
  author_id uuid null,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.workflow_status (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  status text not null,
  changed_by uuid null,
  comment text null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_log_reviews (
  id bigint generated by default as identity primary key,
  daily_log_id bigint not null references public.daily_logs(id) on delete cascade,
  reviewer_id uuid null,
  decision text not null,
  comment text null,
  rejected_activity_id bigint null references public.daily_log_activities(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.daily_logs enable row level security;
alter table public.daily_log_activities enable row level security;
alter table public.daily_log_activity_reports enable row level security;
alter table public.daily_log_activity_photos enable row level security;
alter table public.daily_log_comments enable row level security;
alter table public.workflow_status enable row level security;
alter table public.daily_log_reviews enable row level security;

create index if not exists idx_daily_logs_project_date on public.daily_logs (project_id, log_date desc);
create index if not exists idx_daily_logs_technician_status on public.daily_logs (technician_id, status);
create index if not exists idx_daily_log_activities_daily_log_id on public.daily_log_activities (daily_log_id);
create index if not exists idx_daily_log_activity_reports_activity_id on public.daily_log_activity_reports (activity_id);
create index if not exists idx_daily_log_activity_photos_activity_id on public.daily_log_activity_photos (activity_id);
create index if not exists idx_daily_log_comments_activity_id on public.daily_log_comments (activity_id);
create index if not exists idx_daily_log_reviews_daily_log_id on public.daily_log_reviews (daily_log_id);
