create table if not exists public.ai_summarys (
  id bigint generated by default as identity primary key,
  daily_log_id text not null,
  company_id bigint null,
  project_id bigint null,
  generated_by uuid null references auth.users(id) on delete set null,
  summary_type text not null check (summary_type in ('EXECUTIVE', 'DETAILED')),
  generated_content text not null,
  edited_content text null,
  prompt_version text not null default 'daily-summary-v1',
  ai_provider text not null default 'openai',
  model_name text not null,
  generation_status text not null default 'completed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  daily_log_id text null,
  company_id bigint null,
  project_id bigint null,
  user_id uuid null references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_summarys_daily_log_type on public.ai_summarys (daily_log_id, summary_type, created_at desc);
create index if not exists idx_ai_summarys_generated_by on public.ai_summarys (generated_by);
create index if not exists idx_ai_summarys_project_id on public.ai_summarys (project_id);
create index if not exists idx_ai_audit_events_daily_log_id on public.ai_audit_events (daily_log_id, created_at desc);
create index if not exists idx_ai_audit_events_user_id on public.ai_audit_events (user_id);

alter table public.ai_summarys enable row level security;
alter table public.ai_audit_events enable row level security;

drop policy if exists "Users can view own AI summaries" on public.ai_summarys;
drop policy if exists "Users can insert own AI summaries" on public.ai_summarys;
drop policy if exists "Users can update own AI summaries" on public.ai_summarys;
drop policy if exists "Users can view own AI audit events" on public.ai_audit_events;
drop policy if exists "Service role can insert AI audit events" on public.ai_audit_events;

create policy "Users can view own AI summaries"
  on public.ai_summarys for select
  using (generated_by = auth.uid());

create policy "Users can insert own AI summaries"
  on public.ai_summarys for insert
  with check (generated_by = auth.uid());

create policy "Users can update own AI summaries"
  on public.ai_summarys for update
  using (generated_by = auth.uid())
  with check (generated_by = auth.uid());

create policy "Users can view own AI audit events"
  on public.ai_audit_events for select
  using (user_id = auth.uid());

create policy "Service role can insert AI audit events"
  on public.ai_audit_events for insert
  to service_role
  with check (true);

create or replace function public.update_ai_summarys_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trigger_update_ai_summarys_updated_at on public.ai_summarys;
create trigger trigger_update_ai_summarys_updated_at
  before update on public.ai_summarys
  for each row
  execute function public.update_ai_summarys_updated_at();
