-- Give the bigint primary keys a way to generate themselves.
--
-- 001_base_schema declares projects, concrete_test_logs, concrete_specifications
-- and concrete_delivery_testing_records with "id bigint not null" and no
-- default, no identity, no sequence. Every insert that does not supply an id
-- therefore fails with:
--
--   null value in column "id" of relation "projects" violates not-null constraint
--
-- which is exactly what Add Project hits: the client sends the form fields and
-- expects the database to allocate the key. 001 looks reverse-engineered from a
-- live database whose sequences were never captured, so the defect only shows
-- on projects created since.
--
-- GENERATED BY DEFAULT (not ALWAYS) so existing rows and any explicit-id import
-- keep working. Each sequence starts past the current max so it cannot collide
-- with rows already there. Tables that already have a default are left alone.

do $$
declare
  t text;
  has_default boolean;
  seq text;
begin
  foreach t in array array[
    'projects',
    'concrete_test_logs',
    'concrete_specifications',
    'concrete_delivery_testing_records'
  ] loop
    if to_regclass('public.' || t) is null then
      continue;
    end if;

    select (a.atthasdef or a.attidentity <> '')
      into has_default
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = t
      and a.attname = 'id'
      and a.attnum > 0
      and not a.attisdropped;

    if coalesce(has_default, false) then
      raise notice 'public.% already generates its id, leaving it alone', t;
      continue;
    end if;

    execute format('alter table public.%I alter column id add generated by default as identity', t);
    seq := pg_get_serial_sequence('public.' || t, 'id');
    execute format(
      'select setval(%L, coalesce((select max(id) from public.%I), 0) + 1, false)',
      seq, t
    );
    raise notice 'public.% now generates its id', t;
  end loop;
end $$;
