-- The status history of a field test report.
--
-- reportService.updateReportStatus() has always written to this table, but it
-- was only ever created in the second, unapplied migration folder, so every
-- status change logged "relation does not exist" to the console and the
-- history was lost. The write is wrapped in a catch, which is why nothing
-- looked broken on screen.
--
-- Created here with the same shape the app writes, plus the tenant key every
-- other table carries.

create table if not exists public.report_status_history (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.concrete_test_logs (id) on delete cascade,
  company_id uuid default public.auth_company_id() references public.companies (id),
  from_status text,
  to_status text not null,
  changed_by uuid references auth.users (id) on delete set null,
  changed_by_role text,
  changed_at timestamptz not null default now(),
  comments text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_report_status_history_report on public.report_status_history (report_id);
create index if not exists idx_report_status_history_changed_at on public.report_status_history (changed_at desc);

alter table public.report_status_history enable row level security;

-- Readable with the report it belongs to; written by the person making the
-- change, for a report in their own company.
drop policy if exists "Company members read report status history" on public.report_status_history;
create policy "Company members read report status history" on public.report_status_history
  for select to authenticated
  using (
    public.is_platform_admin()
    or exists (
      select 1 from public.concrete_test_logs c
      where c.id = report_id and c.company_id = public.auth_company_id()
    )
  );

drop policy if exists "Members record report status changes" on public.report_status_history;
create policy "Members record report status changes" on public.report_status_history
  for insert to authenticated
  with check (
    changed_by = auth.uid()
    and exists (
      select 1 from public.concrete_test_logs c
      where c.id = report_id and c.company_id = public.auth_company_id()
    )
  );

-- History is a record: no edits, no deletes, so no policy for either.
