create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  organization_id bigint null,
  project_id bigint null,
  technician_id uuid null,
  log_date date not null default current_date,
  shift text null,
  weather_summary text null,
  supervisor_name text null,
  status text not null default 'draft',
  submitted_at timestamptz null,
  approved_at timestamptz null,
  returned_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_log_activities (
  id bigint generated by default as identity primary key,
  daily_log_id bigint not null references public.daily_logs(id) on delete cascade,
  activity_type text not null,
  title text not null,
  description text null,
  location text null,
  start_time time null,
  end_time time null,
  crew_size text null,
  equipment_used text null,
  material_used text null,
  status text not null default 'not_started',
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_log_activity_reports (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.daily_log_activities(id) on delete cascade,
  report_type text not null,
  linked_report_table text null,
  linked_report_id bigint null,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);

create table if not exists public.daily_log_activity_photos (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.daily_log_activities(id) on delete cascade,
  file_name text not null,
  storage_path text not null,
  compressed_storage_path text null,
  caption text null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_log_comments (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.daily_log_activities(id) on delete cascade,
  author_id uuid null,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.workflow_status (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  status text not null,
  changed_by uuid null,
  comment text null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_log_reviews (
  id bigint generated by default as identity primary key,
  daily_log_id bigint not null references public.daily_logs(id) on delete cascade,
  reviewer_id uuid null,
  decision text not null,
  comment text null,
  rejected_activity_id bigint null references public.daily_log_activities(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.daily_logs enable row level security;
alter table public.daily_log_activities enable row level security;
alter table public.daily_log_activity_reports enable row level security;
alter table public.daily_log_activity_photos enable row level security;
alter table public.daily_log_comments enable row level security;
alter table public.workflow_status enable row level security;
alter table public.daily_log_reviews enable row level security;

create index if not exists idx_daily_logs_project_date on public.daily_logs (project_id, log_date desc);
create index if not exists idx_daily_logs_technician_status on public.daily_logs (technician_id, status);
create index if not exists idx_daily_log_activities_daily_log_id on public.daily_log_activities (daily_log_id);
create index if not exists idx_daily_log_activity_reports_activity_id on public.daily_log_activity_reports (activity_id);
create index if not exists idx_daily_log_activity_photos_activity_id on public.daily_log_activity_photos (activity_id);
create index if not exists idx_daily_log_comments_activity_id on public.daily_log_comments (activity_id);
create index if not exists idx_daily_log_reviews_daily_log_id on public.daily_log_reviews (daily_log_id);

drop policy if exists "Technicians can read own daily logs" on public.daily_logs;
drop policy if exists "Technicians can manage own draft daily logs" on public.daily_logs;
drop policy if exists "Daily log child records follow parent read access" on public.daily_log_activities;
drop policy if exists "Daily log child records follow parent write access" on public.daily_log_activities;

create policy "Technicians can read own daily logs"
  on public.daily_logs for select
  using (technician_id = auth.uid());

create policy "Technicians can manage own draft daily logs"
  on public.daily_logs for all
  using (technician_id = auth.uid())
  with check (technician_id = auth.uid());

create policy "Daily log child records follow parent read access"
  on public.daily_log_activities for select
  using (exists (
    select 1 from public.daily_logs
    where daily_logs.id = daily_log_activities.daily_log_id
      and daily_logs.technician_id = auth.uid()
  ));

create policy "Daily log child records follow parent write access"
  on public.daily_log_activities for all
  using (exists (
    select 1 from public.daily_logs
    where daily_logs.id = daily_log_activities.daily_log_id
      and daily_logs.technician_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.daily_logs
    where daily_logs.id = daily_log_activities.daily_log_id
      and daily_logs.technician_id = auth.uid()
  ));
